config/routes.rb
Rails.application.routes.draw do
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  validates :age, {presence: true, length: {maximum: 20}}
  validates :name, {presence: true, length: {maximum: 20}}
  validates :rent, {presence: true, length: {maximum: 20}}
  validates :adress, {presence: true, length: {maximum: 20}}
  has_many :stations, inverse_of: :room, dependent: :destroy
  accepts_nested_attributes_for :stations, reject_if: proc { |attributes| attributes['route_name'].blank?}
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :room, inverse_of: :stations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
    2.times { @room.stations.build }
  end

  def show
    @room = Room.find(params[:id])
  end

  def edit
    form = @room.stations.count
    if form == 0
      2.times { @room.stations.build }
    elsif form == 1
      1.times { @room.stations.build }
    else
     form+1.times { @room.stations.build }
   end
  end

  def create
    @room = Room.new(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: '作成されました。' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      #if @room.update(room_params)
      if @room.update(update_room_params)
        format.html { redirect_to @room, notice: 'アップデートされました。' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: '削除されました。' }
    end
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name, :rent, :adress, :age, :note, stations_attributes:[:route_name, :station_name, :minutes])
    end

    def update_room_params
      params.require(:room).permit(:name, :rent, :adress, :age, :note, stations_attributes:[:route_name, :station_name, :minutes,:_destroy, :id])
    end
   end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rooms</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: @room, local: true) do |room| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@room.errors.count, "error") %> エラーが発生しました:</h3>
      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      　<% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= room.label :name, "物件名:" %>
    <%= room.text_field :name %>
  </div>

  <div class="field">
    <%= room.label :rent, "賃料:" %>
    <%= room.text_field :rent %>
  </div>

  <div class="field">
    <%= room.label :adress, "住所:" %>
    <%= room.text_field :adress %>
  </div>

  <div class="field">
    <%= room.label :age, "築年数:" %>
    <%= room.text_field :age %>
  </div>

  <div class="field" id="note">
    <%= room.label :note, "備考:" %>
    <%= room.text_area :note %>
  </div>

  <% n = 0 %>
  <%= room.fields_for :stations do |station| %>
    <div class="field">
      <h3>最寄り駅<%= n+= 1 %></h3>
        <%= station.label :route_name, "路線名:" %>
        <%= station.text_field :route_name %>
        <%= station.label :station_name, "駅名:" %>
        <%= station.text_field :station_name %>
        <%= station.label :minutes, "徒歩所要時間:" %>
        <%= station.text_field :minutes %>
    </div>
  <% end %>

  <div class="actions">
    <%= room.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>物件編集</h1>
<%= render 'form', room: @room %>
<%= link_to '詳細', @room %> |
<%= link_to '戻る', rooms_path %>

app/views/rooms/index.html.erb
<h1>物件一覧</h1>

<table>
  <thead>
    <tr>
      <th>物件名:</th>
      <th>賃料:</th>
      <th>住所:</th>
      <th>築年数:</th>
      <th>備考:</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.rent %></td>
        <td><%= room.adress %></td>
        <td><%= room.age %></td>
        <td><%= room.note %></td>
        <td><%= link_to '詳細', room %></td>
        <td><%= link_to '編集', edit_room_path(room) %></td>
        <td><%= link_to '削除', room, method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '物件を登録する', new_room_path %>

app/views/rooms/new.html.erb
<h1>物件登録</h1>

<%= render 'form', room: @room %>

<%= link_to '戻る', rooms_path %>

app/views/rooms/show.html.erb
<h1>閲覧一覧</h1>

<div class="room_basic_information">

<p>
  <strong>物件名:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>賃料:</strong>
  <%= @room.rent %>
</p>

<p>
  <strong>住所:</strong>
  <%= @room.adress %>
</p>

<p>
  <strong>築年数:</strong>
  <%= @room.age %>
</p>

<p>
  <strong>備考:</strong>
  <%= @room.note %>
</p>
</div>

<div class="line"></div>

<% n = 0 %>
<% @room.stations.each do |r| %>
<h4 class="station_infomation_title" id="title1">最寄り駅<%= n+= 1 %></h4>
<div class="near_station_infomation">
  <p>
    <strong>路線名:</strong>
    <%= r.route_name %>
  </p>

  <p>
    <strong>駅名:</strong>
    <%= r.station_name %>
  </p>

  <p>
    <strong>徒歩所要時間:</strong>
    <%= r.minutes %>
  </p>
</div>
<% end %>

<%= link_to '編集', edit_room_path(@room) %> |
<%= link_to '戻る', rooms_path %>